Repository oss2025hnu/reposcore-cs, pull requests merged in 2025-05, with the labels that each got.

#100 유틸리티 오타 수정
  README.md
Labels: typo

#96 reposcore-cs.sln 파일 Git 추적 대상에서 제외
  .gitignore
Labels: enhancement

#101 [DOC] README.md 위치 변경
  README.md
Labels: documentation

#110 github-token-guide.md 오타 수정
  docs/check-env.sh_guide.md
  docs/github-token-guide.md
  reposcore-cs.sln
Labels: typo

#148 README.md 참여조건 삭제
  README.md
Labels: documentation

#171 [DOC] .NET Guide 문서에 명령어 실행 결과 예시 추가 요청
  docs/dotNet-guide.md
Labels: documentation

#203 명령줄 argument로 받는 저장소 정보 형식 개선
  Program.cs
Labels: enhancement

#234 [TYPO] devcontainer.json 쉼표 누락
  .devcontainer/devcontainer.json
Labels: bug

#240 [FEAT] CLI에서 여러 저장소 처리 후 전체 요약 출력 추가 PR
  Program.cs
Labels: enhancement
