Repository oss2025hnu/reposcore-cs, pull requests merged in 2025-06, with the labels that each got.

#276 GitHub Actions에 dotnet build 추가
  .github/workflows/dotnet-build.yml
Labels: enhancement

#266 devcontainer.json에 mustache 추가
  .devcontainer/devcontainer.json
Labels: enhancement

#305 출력 파일을 한 폴더로 통합
  Program.cs
  Reposcore/FileGenerator.cs
Labels: bug

#350 차트의 x축, y축 라벨 영문으로 변경
  Reposcore/FileGenerator.cs
Labels: enhancement

#383 반려된 이슈 제외: 받아들여진 이슈만 점수 합산
  Reposcore/RepoDataCollector.cs
Labels: bug

#388 --user 옵션으로 특정 사용자의 점수 및 순위만 출력 PR
  Program.cs
Labels: enhancement

#399 cache폴더를 .gitignore에 추가
  .gitignore
Labels: enhancement

#466 result > output으로 변경
  Program.cs
Labels: documentation
