Repository oss2025hnu/reposcore-cs, pull requests merged in 2025-04, with the labels that each got.

#5 repository참
  README.md
Labels: documentation

#16 .NET 가이드
  dotNet-guide.md
Labels: documentation

#23 [DOC] dotNet-guide.md 파일 위치 변경
  docs/dotNet-guide.md
Labels: documentation

#31 [Doc]Latex 문법 관련 문제
  README.md
  docs/github-token-guide.md
  docs/images/Fine-grained token.png
  docs/images/Note_Expiration.png
  docs/images/classic_token.png
  docs/images/create_token.png
  docs/images/dev_setting.png
  docs/images/pesonal_access_token.png
  docs/images/setting.png
Labels: typo

#26 dotnet 가이드로 이동하는 링크 추가
  README.md
Labels: typo

#37 README에 프로젝트 가이드라인 설명 추가 (Update README.md)
  README.md
Labels: documentation

#55 Program.cs 및 GitHubAnalyzer.cs에서 C# 문법 오류 발생으로 실행 실패pr
  GitHubAnalyzer.cs
  Program.cs
Labels: bug
